### ISSUE TITLE
Enhance the Configuration file

### ISSUE THREAD

**Issue by edchat** [dmachi/dojox_application#104]
See this link in the 1.9 Plan document for more details:
https://docs.google.com/document/d/1fe2qm1x_AHidYd2wNkG77tZgFIrvlt-ctGT0rpb-5F0/edit?pli=1#heading=h.wslte22n4qh8

Allow a configuration file to share common configuration for example for tablet & phone application without having to copy/paste in 2 configuration files most of the config

**Comment by edchat** [comment]
We can add a configMerge utility which would merge one config into another.  It would add a config item if it did not exist in the original config, or it would overwrite it if it did exist.  But it would want to do a "deep copy" in order to avoid having to include duplicates in the configs.  For example if you want to merge a config which includes the following:

``` javascript
{
    "views": {
        "home": {
            "definition" : "none",
            "template": "../app/tests/simpleModelApp/templates/main.html"
        }
}
```

You would only want to replace the {views.home.definition}, and the {views.home.template}, not the entire {views}, or {views.home}.

Another consideration is how to merge things into Arrays, Since we don't want to have duplicate information in the configuration files, we should "push" the items into the array rather than replace the array.  And it probably does not makes sense to try to replace an item in an array.
So if a config which is be be merged needs to add a dependency, then it would only have to add that dependency and it would be merged in.  So if the config being merged looked like this:

``` javascript
{
    "dependencies": [
        "dojox/mobile/TabBar",
        "dojox/mobile/_compat"
    ]
}
```

Then TabBar and _compat would be added to the list of dependencies.

This branch has a possible implementation: https://github.com/edchat/dojox_application/tree/configMerge
The dojox/app/tests/doh/simpleModelApp/ test uses the configMerge utility in dojox/app/tests/doh/simpleModelApp/ModelApp.js with a calls like these:

``` javascript
var config = configUtils.configMerge(jsonRef.fromJson(config1), jsonRef.fromJson(configMerge));

config = has("ie") ? configUtils.configMerge(config,{"controllers": ["dojox/app/controllers/HistoryHash"]}) : 
                configUtils.configMerge(config,{"controllers": ["dojox/app/controllers/History"]})      

```

**Comment by cjolif** [comment]
An alternate possibility would be to have a single config file and have the config syntax reflects one way or another than certain items apply only to a given device. This could be matched against equivalent "has" flags when the config is interpreted.

**Comment by edchat** [comment]
It seems to me that if we are going to try to use one json config file with some config syntax to handle differences for different devices (or other things) we will no longer have valid JSON in our config files.  

I guess we could do something like that if we put our config inside our javascript as an object instead of an actual json file, but there are advantages to having valid JSON in the config file.  

dojox/json/ref.js (which we currently use to call fromJson) has support for a {$ref} syntax to reference something from the json, (like this: b:{$ref:"#.c"}) but it does not seem to have support to ref something from outside of the json on the call to fromJson() which I think we would need, we would also need some kind of if/else logic.

**Comment by cjolif** [comment]
I agree which should try to keep our config file JSON-compliant, but maybe can still keep compliance?

I think there are two main cases. There is the branching case (you want two or more branches entirely different for each devices) and there is the case where we want an additional item in an existing list of items when running on a particular device.

The first case might be solvable by using a specific "device" child and the second by a specific "devices" attribute. Something like the following:

```
{
    "id": "todoApp",
    "name": "ToDo App",

    "loaderConfig":
                "device": {
                       "all": {
                  "paths": { "todoApp": "../demos/todoApp" }
                        },
                       "desktop": {
                  "paths": { "todoAppDesktopJS": "../demos/todoApp/dt" }
                       }
        }
    },

    "dependencies": 
                    "device": {
                       "all": [ ...],
                       "ios: [...]
                      }               
    ],
        // if the device child is not present, then we treat the value as usual (applies to "all")
    "modules": [
        "todoApp/todoApp"
    ],

        // to enable a view only for a subset of devices you can also use the devices attribute on it
    "views": {
               "a" : {
                  "devices": "Android, iOS",
               },
             ....
         }
}
```

I'm not sure this is perfect but I think we should really do our best to avoid asking people to do the merge themselves in the application code (in particular as this would force changing the application code when updating the config).

**Comment by dmachi** [comment]
Actually, I don't know that the dependencies section needs to split in this way.  It could be done like this:   The dependencies prop only contain all of the global dependencies (across all platforms) and then specific view are included with that specific view.  Each view can be tagged with the runtime environments it should support, and so views specific to a target can include their special dependencies there.  All that said, we could still do something similar to the dependencies prop listed below.    I'm not sure I understand the loaderConfig section.  Is this basically loading a different app altogether for a specific situation?  I'd prefer to use $refs and never require actual merging of config files (though allowing a config file to be split into multiple sub files is necessary).

Dustin

**Comment by edchat** [comment]
I don't think adding support for "device" or "devices" will be flexible enough, currently the two cases we have for different configs is for phone vs tablet and the "IE" browser case for History vs. HistoryHash, it seems that neither of these would be solved by a "device" check.  I agree that there will be other cases where the device check would work, but I think we need to have support that will also solve the tablet case and have some way to handle other generic tests like we would need for "IE".  

I guess we could extend the dojox.json.ref.js code (or write our own code) to do some substitution and processing along with the fromJson processing, to substitute values and remove un-needed sections.  That may still require some code in the app's js file to to setup some variables before processing the json.  Maybe we could try to process any $xxx variable (including $device)?  And we could define some variables that we would always have available like device, (and maybe browser...).

Christophe thanks for adding the section of config along with the proposal, it is helpful to see how the config would look for the different suggestions.

**Comment by dmachi** [comment]
On Oct 1, 2012, at 9:53 AM, Ed Chatelain wrote:

> I don't think adding support for "device" or "devices" will be flexible enough, currently the two cases we have for different configs is for phone vs tablet and the "IE" browser case for History vs. HistoryHash, it seems that neither of these would be solved by a "device" check. I agree that there will be other cases where the device check would work, but I think we need to have support that will also solve the tablet case and have some way to handle other generic tests like we would need for "IE".

Sure, however I think in practice it can boil down a little bit differently.   The top level of categorizations is:
1. Browser only web applications.  These basically just web apps with no special attention given to mobile versions or specifics.
2. Mobile and Browser Web applications.  These are web apps that provide an experience for web applications and a different/specialized experience for mobile applications.
3. Distributed Device applications.  These are built and packaged to be deployed and executed either directly on a device (or specific browser) or served to specific a specific type of device only.

In the first case, Browser only web applications, we are generally talking about a standard dojo web application in terms of loading and building.  Any detection of browser for browser specific use cases should follow the same patterns we are moving towards with dojo/dijit as a whole.  In other words, browser branching should be done using feature detection.  Static builds for a specific device are done using predefined has() maps.  We should allow our config to have has() definition in it. 

In the second case, we still want to follow this same basic pattern of using has maps.  The main difference in this section is sizes of devices have much more variety that impacts the desired layout than do standard web applications.  

In both of these cases however, we want to create builds that will simultaneously serve the correct dependency tree up to clients.  This doesn't imply that there needs to be a single js file built for an application or that an application be built at all.   So a build could generate something like this:

common.js
desktop-common.js
mobile-common.js
desktop.js
iOS.js
android.js
titanium.js

The actual app module served to the application would ultimately require one set of these, say common, mobile-common, and iOS  to load on an iPhone. 

In the third case, only a single device specific build is generated so it is the only one that really gets to ignore of the available dependency information.  

The main point of all this however, is that this is still generally an issue of generating tests and using has to let this be worked out by the build/dependency system naturally. As long as we generate a proper set of has() checks and uses, we should have the information we need to generate a set of files similar to those above.  I'm thinking we should do something like this:
1.  Allow has checks to be user defined (and we should supply some standard ones) that the config can automatically execute during initialization.  The developer should be able to define the list of which checks should be executed automatically at startup and empty otherwise. If a specific app has no need to branch at high levels, it shouldn't' be forced to use anything.
2.  Allow a has() tree to be defined (but not required) in the config.  This is the equivalent of predefining/overriding any check's.   It might be desirable to define these in a separate file and allow the build command to define which ones to import/build. This is the piece that would allow specific targeted builds to be created, but still allows the developer to define what they configure to be 'classes' of apps (mobile/desktop/deployed).  
3.  Allow the developer to define (in the config) an initialization function which runs after the define has checks have been executed, but before the applications main startup has been called.  This allows the developer to modify the way the application will startup/execute by modifying the configuration at runtime before the application starts itself.  Because these are runtime decisions, it doesn't impact the build generally.
4.  The 'build' system should probably just be a small node script that reads our config file and some options and generates a config file that the dojo builder can consume to create the build.  Our script can automatically call dojo against this config file of course, but it provides a very useful point of debugging problems and separation between application code and the build system. 

I'll also review the 'app' predefinition thing I had done before, as I can't remember specifically why I had to do that at the time, but I believe it was because of the generated nature of things.  I will check and see if that can be done differently now.  

> I guess we could extend the dojox.json.ref.js code (or write our own code) to do some substitution and processing along with the fromJson processing, to substitute values and remove un-needed sections. That may still require some code in the app's js file to to setup some variables before processing the json. Maybe we could try to process any $xxx variable (including $device)? And we could define some variables that we would always have available like device, (and maybe browser…)

In terms of the $ref code automatically loading things, there is a way to configure that to make it work (I think you can provide it a resolving function, but I don't' remember the details for sure.  I've done it before though).  It depends in this case on when and for what purpose we need to load it for.  For example it is different when needing to load one of the $refs in order to create a build vs what it needs to do to load an app from a browser or device.  All that said, I think it can be accomplished because the information exists already in the config file.  

I'm kind of mixed on the $variable thing at the moment.  It does seem like it could be useful at a glance, but I'm having trouble of thinking of a real use for it that wouldn't' already be solved by using has() in the way i described above.  I think it could expand and get ugly, but I think we can defer on this one for the time being if the has() solution satisfies. 

Note that feature tests could be things like isBrowser() or isDevice() type of detection.  While real detection of features is of course desirable as the functionality behind these types of methods, I'm also practical when the options on how to do or define what set of features make a device or browser.

Dustin

**Comment by edchat** [comment]
Hi Dustin,
    It is good that you are thinking about this from a build perspective
too, I was focusing on making it easier to setup the config and avoiding
duplication and multiple configs.
Questions below in line:

On Mon, Oct 1, 2012 at 11:13 AM, Dustin Machi notifications@github.comwrote:

> On Oct 1, 2012, at 9:53 AM, Ed Chatelain wrote:
> 
> > I don't think adding support for "device" or "devices" will be flexible
> > enough, currently the two cases we have for different configs is for phone
> > vs tablet and the "IE" browser case for History vs. HistoryHash, it seems
> > that neither of these would be solved by a "device" check. I agree that
> > there will be other cases where the device check would work, but I think we
> > need to have support that will also solve the tablet case and have some way
> > to handle other generic tests like we would need for "IE".
> 
> Sure, however I think in practice it can boil down a little bit
> differently. The top level of categorizations is:
> 1. Browser only web applications. These basically just web apps with no
>    special attention given to mobile versions or specifics.
> 2. Mobile and Browser Web applications. These are web apps that provide an
>    experience for web applications and a different/specialized experience for
>    mobile applications.
> 3. Distributed Device applications. These are built and packaged to be
>    deployed and executed either directly on a device (or specific browser) or
>    served to specific a specific type of device only.
> 
> In the first case, Browser only web applications, we are generally talking
> about a standard dojo web application in terms of loading and building. Any
> detection of browser for browser specific use cases should follow the same
> patterns we are moving towards with dojo/dijit as a whole. In other words,
> browser branching should be done using feature detection. Static builds for
> a specific device are done using predefined has() maps. We should allow our
> config to have has() definition in it.

How are you thinking we would support the has() definition in the config?

> In the second case, we still want to follow this same basic pattern of
> using has maps. The main difference in this section is sizes of devices
> have much more variety that impacts the desired layout than do standard web
> applications.
> 
> In both of these cases however, we want to create builds that will
> simultaneously serve the correct dependency tree up to clients. This
> doesn't imply that there needs to be a single js file built for an
> application or that an application be built at all. So a build could
> generate something like this:
> 
> common.js
> desktop-common.js
> mobile-common.js
> desktop.js
> iOS.js
> android.js
> titanium.js
> 
> The actual app module served to the application would ultimately require
> one set of these, say common, mobile-common, and iOS to load on an iPhone.
> 
> In the third case, only a single device specific build is generated so it
> is the only one that really gets to ignore of the available dependency
> information.
> 
> The main point of all this however, is that this is still generally an
> issue of generating tests and using has to let this be worked out by the
> build/dependency system naturally. As long as we generate a proper set of
> has() checks and uses, we should have the information we need to generate a
> set of files similar to those above. I'm thinking we should do something
> like this:
> 1. Allow has checks to be user defined (and we should supply some standard
>    ones) that the config can automatically execute during initialization. The
>    developer should be able to define the list of which checks should be
>    executed automatically at startup and empty otherwise. If a specific app
>    has no need to branch at high levels, it shouldn't' be forced to use
>    anything.

If we can do this, I agree that would remove the need for the $variable as
you say below.

> 1. Allow a has() tree to be defined (but not required) in the config. This
>    is the equivalent of predefining/overriding any check's. It might be
>    desirable to define these in a separate file and allow the build command to
>    define which ones to import/build. This is the piece that would allow
>    specific targeted builds to be created, but still allows the developer to
>    define what they configure to be 'classes' of apps
>    (mobile/desktop/deployed).

Again the same question as above, what syntax do you see for this?  Is it
valid json in the config.json file?

> 1. Allow the developer to define (in the config) an initialization
>    function which runs after the define has checks have been executed, but
>    before the applications main startup has been called. This allows the
>    developer to modify the way the application will startup/execute by
>    modifying the configuration at runtime before the application starts
>    itself. Because these are runtime decisions, it doesn't impact the build
>    generally.
> 2. The 'build' system should probably just be a small node script that
>    reads our config file and some options and generates a config file that the
>    dojo builder can consume to create the build. Our script can automatically
>    call dojo against this config file of course, but it provides a very useful
>    point of debugging problems and separation between application code and the
>    build system.
> 
> By this do you mean that we would have a build step during development?
> If so I think that would not be ideal.
> 
> I'll also review the 'app' predefinition thing I had done before, as I
> can't remember specifically why I had to do that at the time, but I believe
> it was because of the generated nature of things. I will check and see if
> that can be done differently now.
> 
> > I guess we could extend the dojox.json.ref.js code (or write our own
> > code) to do some substitution and processing along with the fromJson
> > processing, to substitute values and remove un-needed sections. That may
> > still require some code in the app's js file to to setup some variables
> > before processing the json. Maybe we could try to process any $xxx variable
> > (including $device)? And we could define some variables that we would
> > always have available like device, (and maybe browser…)
> 
> In terms of the $ref code automatically loading things, there is a way to
> configure that to make it work (I think you can provide it a resolving
> function, but I don't' remember the details for sure. I've done it before
> though). It depends in this case on when and for what purpose we need to
> load it for. For example it is different when needing to load one of the
> $refs in order to create a build vs what it needs to do to load an app from
> a browser or device. All that said, I think it can be accomplished because
> the information exists already in the config file.
> 
> I'm kind of mixed on the $variable thing at the moment. It does seem like
> it could be useful at a glance, but I'm having trouble of thinking of a
> real use for it that wouldn't' already be solved by using has() in the way
> i described above. I think it could expand and get ugly, but I think we can
> defer on this one for the time being if the has() solution satisfies.
> 
> Note that feature tests could be things like isBrowser() or isDevice()
> type of detection. While real detection of features is of course desirable
> as the functionality behind these types of methods, I'm also practical when
> the options on how to do or define what set of features make a device or
> browser.
> 
> Dustin

I think all of this would be much easier to follow if we can come up with
some sample configs to look at.  Maybe we could start with the config files
being used for the todoApp demo?  Once you let me know how you are thinking
to handle the has mapping in the config, I will try to update the todoApp
config (not to run it, but only to see how the config looks) and we can go
from there.

Thanks,
Ed

**Comment by edchat** [comment]
Sorry, my last comment did not show up correctly when I sent it.  I have edited it now.

**Comment by dmachi** [comment]
On Oct 1, 2012, at 12:50 PM, Ed Chatelain wrote:

> Hi Dustin, 
> It is good that you are thinking about this from a build perspective 
> too, I was focusing on making it easier to setup the config and avoiding 
> duplication and multiple configs. 
> Questions below in line: 
> 
> On Mon, Oct 1, 2012 at 11:13 AM, Dustin Machi notifications@github.comwrote: 
> 
> > On Oct 1, 2012, at 9:53 AM, Ed Chatelain wrote: 
> > 
> > > I don't think adding support for "device" or "devices" will be flexible 
> > > enough, currently the two cases we have for different configs is for phone 
> > > vs tablet and the "IE" browser case for History vs. HistoryHash, it seems 
> > > that neither of these would be solved by a "device" check. I agree that 
> > > there will be other cases where the device check would work, but I think we 
> > > need to have support that will also solve the tablet case and have some way 
> > > to handle other generic tests like we would need for "IE". 
> > 
> > Sure, however I think in practice it can boil down a little bit 
> > differently. The top level of categorizations is: 
> > 1. Browser only web applications. These basically just web apps with no 
> >    special attention given to mobile versions or specifics. 
> > 2. Mobile and Browser Web applications. These are web apps that provide an 
> >    experience for web applications and a different/specialized experience for 
> >    mobile applications. 
> > 3. Distributed Device applications. These are built and packaged to be 
> >    deployed and executed either directly on a device (or specific browser) or 
> >    served to specific a specific type of device only. 
> > 
> > In the first case, Browser only web applications, we are generally talking 
> > about a standard dojo web application in terms of loading and building. Any 
> > detection of browser for browser specific use cases should follow the same 
> > patterns we are moving towards with dojo/dijit as a whole. In other words, 
> > browser branching should be done using feature detection. Static builds for 
> > a specific device are done using predefined has() maps. We should allow our 
> > config to have has() definition in it. 
> > 
> > How are you thinking we would support the has() definition in the config? 

We'd just have a "has" array in the config that would execute all the tests defined before calling the initialization function i mentioned below.  When the build is run we might have a script that would be like "build -has mobile.js app.'s"  which would read the object in mobile.js and use that to override the has property of has in app's config.js.  if you don't define anything it should just do a build for all of the has overrides.

> > In the second case, we still want to follow this same basic pattern of 
> > using has maps. The main difference in this section is sizes of devices 
> > have much more variety that impacts the desired layout than do standard web 
> > applications. 
> > 
> > In both of these cases however, we want to create builds that will 
> > simultaneously serve the correct dependency tree up to clients. This 
> > doesn't imply that there needs to be a single js file built for an 
> > application or that an application be built at all. So a build could 
> > generate something like this: 
> > 
> > common.js 
> > desktop-common.js 
> > mobile-common.js 
> > desktop.js 
> > iOS.js 
> > android.js 
> > titanium.js 
> > 
> > The actual app module served to the application would ultimately require 
> > one set of these, say common, mobile-common, and iOS to load on an iPhone. 
> > 
> > In the third case, only a single device specific build is generated so it 
> > is the only one that really gets to ignore of the available dependency 
> > information. 
> > 
> > The main point of all this however, is that this is still generally an 
> > issue of generating tests and using has to let this be worked out by the 
> > build/dependency system naturally. As long as we generate a proper set of 
> > has() checks and uses, we should have the information we need to generate a 
> > set of files similar to those above. I'm thinking we should do something 
> > like this: 
> > 1. Allow has checks to be user defined (and we should supply some standard 
> >    ones) that the config can automatically execute during initialization. The 
> >    developer should be able to define the list of which checks should be 
> >    executed automatically at startup and empty otherwise. If a specific app 
> >    has no need to branch at high levels, it shouldn't' be forced to use 
> >    anything. 
> > 
> > If we can do this, I agree that would remove the need for the $variable as 
> > you say below. 

We do it for dojo, so I don't see any reason for it to be different here. Trying to boil things down to a single target is what is difficult. If what gets built is dependent on what features the env actually has and so that can be forced to do a build for a particular case should cover us as it does with dojo itself.

> > 1. Allow a has() tree to be defined (but not required) in the config. This 
> >    is the equivalent of predefining/overriding any check's. It might be 
> >    desirable to define these in a separate file and allow the build command to 
> >    define which ones to import/build. This is the piece that would allow 
> >    specific targeted builds to be created, but still allows the developer to 
> >    define what they configure to be 'classes' of apps 
> >    (mobile/desktop/deployed). 
> > 
> > Again the same question as above, what syntax do you see for this? Is it 
> > valid json in the config.json file? 
> 
> Yes valid json in the config.json file.  If a -has option is provided as described above, that would be read in as an array and replace the has property on config.json.  For views, they can simply be tagged with appropriate environments.   Does that answer your question?
> 
> > 1. Allow the developer to define (in the config) an initialization 
> >    function which runs after the define has checks have been executed, but 
> >    before the applications main startup has been called. This allows the 
> >    developer to modify the way the application will startup/execute by 
> >    modifying the configuration at runtime before the application starts 
> >    itself. Because these are runtime decisions, it doesn't impact the build 
> >    generally. 
> > 2. The 'build' system should probably just be a small node script that 
> >    reads our config file and some options and generates a config file that the 
> >    dojo builder can consume to create the build. Our script can automatically 
> >    call dojo against this config file of course, but it provides a very useful 
> >    point of debugging problems and separation between application code and the 
> >    build system. 
> > 
> > By this do you mean that we would have a build step during development? 
> > If so I think that would not be ideal. 

The build should NOT be required during development.  This is for building an application that can be used in production or deployed to a device if appropriate.

> > I'll also review the 'app' predefinition thing I had done before, as I 
> > can't remember specifically why I had to do that at the time, but I believe 
> > it was because of the generated nature of things. I will check and see if 
> > that can be done differently now. 
> > 
> > > I guess we could extend the dojox.json.ref.js code (or write our own 
> > > code) to do some substitution and processing along with the fromJson 
> > > processing, to substitute values and remove un-needed sections. That may 
> > > still require some code in the app's js file to to setup some variables 
> > > before processing the json. Maybe we could try to process any $xxx variable 
> > > (including $device)? And we could define some variables that we would 
> > > always have available like device, (and maybe browser…) 
> > 
> > In terms of the $ref code automatically loading things, there is a way to 
> > configure that to make it work (I think you can provide it a resolving 
> > function, but I don't' remember the details for sure. I've done it before 
> > though). It depends in this case on when and for what purpose we need to 
> > load it for. For example it is different when needing to load one of the 
> > $refs in order to create a build vs what it needs to do to load an app from 
> > a browser or device. All that said, I think it can be accomplished because 
> > the information exists already in the config file. 
> > 
> > I'm kind of mixed on the $variable thing at the moment. It does seem like 
> > it could be useful at a glance, but I'm having trouble of thinking of a 
> > real use for it that wouldn't' already be solved by using has() in the way 
> > i described above. I think it could expand and get ugly, but I think we can 
> > defer on this one for the time being if the has() solution satisfies. 
> > 
> > Note that feature tests could be things like isBrowser() or isDevice() 
> > type of detection. While real detection of features is of course desirable 
> > as the functionality behind these types of methods, I'm also practical when 
> > the options on how to do or define what set of features make a device or 
> > browser. 
> > 
> > Dustin 
> 
> I think all of this would be much easier to follow if we can come up with 
> some sample configs to look at. Maybe we could start with the config files 
> being used for the todoApp demo? Once you let me know how you are thinking 
> to handle the has mapping in the config, I will try to update the todoApp 
> config (not to run it, but only to see how the config looks) and we can go 
> from there. 

I'll make some example config files send them to you / here for discussion.  I thin this will be the easiest way because it follows the existing machinery instead of developing new machinery for dojox/app

Dustin

**Comment by edchat** [comment]
Dustin, if you can give me a sample config of how you think it should be specified, I will see if I can get it to work.

**Comment by edchat** [comment]
I have made another attempt at getting moving on this support.  The latest is in my hasconfig branch here:
https://github.com/edchat/dojox_application/tree/hasconfig

I am sure there will be more discussion, but basically I tried to take a combination of the suggestions from cjolif and dmachi.  This code supports having "has" sections in the config, along with a hasList of has checks which can be used to determine which of the items in the "has" section should be included and which should be removed.

As a simple example if a config wanted to have a different defaultView for a phone and tablet, and it wanted a different controller for ie it could set up a has section like this:

``` javascript
    "has" : {
        "phone" : {
            "defaultView": "configuration,ScrollableListSelection",
        },
        "tablet" : {
            "defaultView": "configuration+TestInfo"
        },
        "ie" : {
            "controllers": [
                "dojox/app/controllers/HistoryHash",
            ]
        },
        "notIE" : {
            "controllers": [
                "dojox/app/controllers/History",
            ]
        }
    },  
```

There could be different "has" sections at different levels of the config, so you could also have another "has" section under a view like this, which would setup the configuration view differently for a phone vs. tablet:

``` javascript
        "configuration": {
                "has" : {
                    "phone" : {
                        "defaultView": "ScrollableListSelection",
                        "transition": "slide",
                        "definition": "none",
                        "views": {
                            "ScrollableListSelection": {
                                "template": "scrollableTestApp/templates/configuration/ScrollableListSelection.html"
                            }
                        }
                    },
                    "tablet" : { 
                        "template": "scrollableTestApp/templates/configuration/ScrollableListSelection.html",
                        "definition": "scrollableTestApp/views/configuration/ScrollableListSelection.js",
                        "constraint" : "left",
                    },  
                },
        },
```

Currently I have it working where the code which sets up the config sets up the hasList and calls the util to process the has sections like this:

``` javascript
require(["dojox/app/main","dojox/app/utils/configUtils",  "dojox/json/ref", "dojo/sniff"],
    function(Application, configUtils, json, has){
    var isTablet = false;
    var configurationFile = "./config-test.json";
    if(window.innerWidth > 600){
        isTablet = true;
    }
    require(["dojo/text!"+configurationFile], function(configJson){
        var hasList = {};
        hasList["tablet"] = isTablet;
        hasList["phone"] = !isTablet;
        hasList["notIE"] = !has("ie");
        var config = configUtils.configProcessHas(json.fromJson(configJson),hasList);
        console.log("back from configProcessHas has config = ",config);
        config.isTablet = isTablet;
        Application(config);
    });
});
```

**Comment by edchat** [comment]
The code was changed so that the hasList is no longer used, the app would just have to use has.add(...) to add the has checks used in the config, like this:

``` javascript
require(["dojox/app/main","dojox/app/utils/config",  "dojox/json/ref", "dojo/sniff"],
    function(Application, configUtil, json, has){
    var isTablet = false;
    var configurationFile = "./config.json";
    if(window.innerWidth > 600){
        isTablet = true;
    }
    require(["dojo/text!"+configurationFile], function(configJson){
        has.add("tablet", isTablet);
        has.add("phone", !isTablet);
        has.add("ie9orLess", has("ie") && !has("ie") >= 10);
        has.add("notie9orLess", !has("ie") || has("ie") >= 10);
        var config = json.fromJson(configJson);
        Application(config);
    });
});
```

**Comment by edchat** [comment]
The last update to the has config support was to add ! support, so you can now have a has section like this:

``` javascript
    "has" : {
        "phone" : {
            "defaultView": "configuration",
            "isTablet" : false
        },
        "!phone" : {
            "defaultView": "configuration+TestInfo",
            "isTablet" : true
        },
        "ie9orLess" : {
            "controllers": [
                "dojox/app/controllers/HistoryHash"
            ]
        },
        "!ie9orLess" : {
            "controllers": [
                "dojox/app/controllers/History"
            ]
        }
    },  
```

And you only have to call has.add() for phone and ie9orLess for those checks.
I think with this update we can close this issue.
