### ISSUE TITLE
Globalization support

### ISSUE THREAD

**Issue by edchat** [dmachi/dojox_application#105]
Globalization support. In particular make sure parameters of the configuration (name, description...) can be localized and that the user can specify a nls path in the config for their views

See more details in the 1.9 plan:
https://docs.google.com/document/d/1fe2qm1x_AHidYd2wNkG77tZgFIrvlt-ctGT0rpb-5F0/edit?pli=1#heading=h.cqfn9x4yiu3f

**Comment by damiengarbarino** [comment]
Maybe a useful addition would be to add a global nls at the application level. 
For example, I have one single nls file and several views. I need to declare the same nls in each view definition.
Thanks

**Comment by cjolif** [comment]
Another (more complex) suggestion that was done is to have nls cascading from parent to child views.

@edchat  can you re-open the issue so we don't forget about that? Thanks.

**Comment by cjolif** [comment]
@edchat now that #149 has been merged, I think that one can be closed again.
