### ISSUE TITLE
View Loading, allow direct loading of a Widget

### ISSUE THREAD

**Issue by edchat** [dmachi/dojox_application#106]
Be even more flexible in view templates/definition loading:
Allow direct loading of Widget/programmatic views (instead of just HTML templates)

**Comment by lyleunderwood** [comment]
+1

is there a way to point at a view subclass in the config? I wanted to put together a view subclass which could point at a widget.

what sucks most about this is that i have no simple method of utilizing dojo's template functionality like data-dojo-attach-point etc.

i just want to do:

``` json
"views": {
   "home": "app/views/home"
}
```

where app/views/home points at a subclass of View.

**Comment by cjolif** [comment]
for data-dojo-attach-\* see also #22

**Comment by cjolif** [comment]
Was closed by #135 with example in customApp.
