### ISSUE TITLE
Build System Integration

### ISSUE THREAD

**Issue by edchat** [dmachi/dojox_application#108]
Build system should be extended to support dojox/app JSON config (i.e. automatically look up in their to build the corresponding source files).
Some issues with build should be investigated and fixed. For example the fact that dojox/app automatically maps “./” modules to an “app” module might cause problem to load “built” files.

**Comment by cjolif** [comment]
See work in this branch https://github.com/cjolif/dojox_application/tree/buildsystem of my fork

**Comment by edchat** [comment]
thanks cjolif
