### ISSUE TITLE
Model objects with business logic can't be used with EditModelRefController

### ISSUE THREAD

**Issue by itamarro** [dmachi/dojox_application#113]
Let's assume I am using a model object with some simple business logic inside it, for instance an isValid() method, and I'd like to use EditModelRefController to manage this model object.

Since EditModelRefController.reset() uses cloneModel() internally, a call to reset() results in a new object managed by the EditModelRefController instance - where this new data object indeed has the same data fields as the original -  but one that does not contain the isValid() method. This causes any controller code which relies on such business methods to malfunction.

I'm not yet sure what would be the most appropriate way to handle this in practice, but I think it's a very real concern when implementing apps.

**Comment by cjolif** [comment]
isn't that a dojox/mvc issue more than a dojox/app one? if yes it should probably be moved to trac.

**Comment by itamarro** [comment]
Hmm, I guess so, sorry - was not aware of this separation of concerns :) I've created a bug there: http://bugs.dojotoolkit.org/ticket/16109

**Comment by edchat** [comment]
Closing this since it was moved to trac for dojox/mvc
