### ISSUE TITLE
address bar hiding on ios/safari problem with sizing

### ISSUE THREAD

**Issue by edchat** [dmachi/dojox_application#122]
This issue was raised here: 
https://github.com/cjolif/dojo-todo-app/issues/102
by maitriyogin: 

Setting mblHideAddressBar and mblAlwaysHideAddressBar to true hides the address bar.
However the containers are not resized to with the new space.
It seems that the layout is done before the address bar is hidden..
Any ideas?
Cheers,
Stephen.

I have recreated the problem.

**Comment by edchat** [comment]
This should now be fixed with what is in github and svn, for both 1.8 and trunk.  It should be included in 1.8.2 when it ships.

**Comment by maitriyogin** [comment]
cool!
huge thanks,
Maitriyogin
