### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by maitriyogin** [dmachi/dojox_application#130]
Hi,
I'm currently trying to do a build of our dojox/app application and am using the dojo-boilerplate as a starting base.
I can get the build working although when I try and go into my index.html I get the infamous :Error: declare: mixin #1 is not a callable constructor. on ln 109 of dojo.js ( which is now compressed ).
I know this is probably not an issue and I'v given a hugely brief overview of my problem, but before I start picking stuff apart I thought it wise to ask if there was a "preferred way" of doing a dojox/app build?

Many thanks,
Stephen.

File structure -
webapp/
            /build.sh
            /profiles/app.profile.js
            /src
                  /app <- contains standard app structure
                  /app/run.sh <- contains package info for the build
                  /dojo
                  /dijit
                  /dojox
                  /util

**Comment by cjolif** [comment]
We are working on easing that in 1.9. See: https://github.com/dmachi/dojox_application/pull/121

Maybe you can try to apply that to 1.8 (at your own risk).

**Comment by maitriyogin** [comment]
Hi Christophe,
Many thanks for the reply.
The limitations section was something I came up against immediately, with the relative ./ of for the views.
The build puts a module name in each view.js define : define("appName/views/login/LoginForm",
I had to include these module names in the definitions of my views :

"LoginForm" : {

"template": "./templates/login/LoginForm.html",

```
    "definition":"appName/views/login/LoginForm"
```

}

/Stephen.

On 11/22/12 16:47 , "Christophe Jolif" <notifications@github.com<mailto:notifications@github.com>> wrote:

We are working on easing that in 1.9. See: #121https://github.com/dmachi/dojox_application/issues/121

Maybe you can try to apply that to 1.8 (at your own risk).
