### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by lyleunderwood** [dmachi/dojox_application#137]
i'm getting the following against master:

```
/parserExtension
c/parserExtension
error(311) Missing dependency. module: dojox/app/build/buildControlApp; dependency: build/buildControlDefault
error(311) Missing dependency. module: dojox/app/build/discoverAppConfig; dependency: build/argv
error(311) Missing dependency. module: dojox/app/build/discoverAppConfig; dependency: build/fs
error(311) Missing dependency. module: dojox/app/build/discoverAppConfig; dependency: build/buildControl
error(311) Missing dependency. module: dojox/app/build/discoverAppConfig; dependency: build/messages
error(311) Missing dependency. module: dojox/app/build/discoverAppConfig; dependency: build/process
```

all i did was drop master in dojox/app in a dojo boilerplate application. it seems to work fine except for building. am i missing something?

**Comment by cjolif** [comment]
These classes are not meant to be built they are themselves extensions to Dojo build system to help building dojox/app apps.
Are you using dojo trunk? or dojo 1.8? With trunk those should be exclude from the build and you should not have the problem. For 1.8 you will have to exclude them manually.

**Comment by lyleunderwood** [comment]
ah yes, i had the wrong branch checked out.

my question becomes, what is the status of the build process currently? I noticed in the only test app with a build profile the following lines are added:

``` javascript
require(["dojox/app/build/buildControlApp"], function(bc){
});
```

this seems to be loading correctly, but i'm not sure what purpose it serves. what's the best way to use dojox/app in conjunction with the dojo builder to put together layers?

**Comment by cjolif** [comment]
We have introduced build system extension in master/1.9. In 1.8 you are on your own (build your own profile).

Have you looked the doc? http://livedocs.dojotoolkit.org/dojox/app#building-an-application does it answer your questions?
