### ISSUE TITLE
confusing terminology/directory names

### ISSUE THREAD

**Issue by ccmitchellusa** [dmachi/dojox_application#15]
This is something that's become more obvious as we've begun to use dojox_application for apps like https://github.com/cjolif/dojo-todo-app and getting feedback from several teams trying to use the latest dojox/app.

The directories views/ and templates/ seem misnamed, based on their role/mapping to commonly known MVC terminology.

The templates in this mvc style are really the View part of MVC.
The js files in the views/ directory of dojox.app projects are really the Controllers logic of MVC.
"Scenes" in dojox.app are really what are commonly known as "Composite Controllers" in MVC terms.

The terminology we should use where this is confusing is coming from what's being taught in universities around MVC...especially modern mobile/iOS development courses.  I think we should try to get our overall concepts aligned with what students are being taught that MVC is (really this hasn't changed much since early smalltalk days), so that the mental mapping when they come to dojo is minimal and obvious.

As a concrete example of a course and terminology that's being taught, check out iTunesU-> Stanford University-> Developing Apps for iOS CS193P (2011) course by Paul Hegarty, specifically the second part of Lecture 1: MVC and Lecture 6: Multiple MVC's and Segues. 

We should be able to describe dojox.app and dojox.mvc with obvious relation to the concepts in these lectures (even though this is a course for native app development, the exact concepts apply to what we're doing).

We should consider renaming the directories to match this more logical mapping. it helps remove the extra made-up term, "templates" that doesn't mean anything in mvc sense.

templates/ ==> views/
views/ ==> controllers/
"scene" ==> "composite controller"

**Comment by eric-wang** [comment]
templates: template files, it's better to have the folder structure the same as view configuration in the configuration file
views: view definition, it's better to have the folder structure the same as view configuration in the configuration file, dojox.app will load view definition by default. If a view not has its own definition, set "definition" to "none" in the view's configuration. Also, uses can set "definition" to the view's definition file path

**Comment by itamarro** [comment]
+1 to @ccmitchellusa's comment. In a reasonably-designed app you'd have view definitions (in the configuration) referring to objects which are definitely controllers - highlighting this discrepancy.

**Comment by edchat** [comment]
The recommended file structure has changed to have the view controller (.js files) and the view template (.html files) in the same directory.  And the names under a view has changed to use template for the .html file and controller for the .js file.  I think this solves this issue.
