### ISSUE TITLE
Problem with transition type, and which should take precedence when there is a defaultTransition in the config, and a transition is set on the transition event.

### ISSUE THREAD

**Issue by edchat** [dmachi/dojox_application#151]
Currently if a defaultTransition is set it the config, it is always used, and a transition set on a transition event is ignored,
that is not good, but there is another problem in that dojox/mobile/RoundRectList sets a default transition to "slide", so for an item in a RoundRectList it will never use the defaultTransition even if it was not set by the app.
I am proposing adding a transition option to the config which would take precedence over the transition event and the defaultTransition.  So if an app wants to force the transition from the config transition can be used, if not transition should be avoided and the transition can be set on the transition event or in defaultTranstion.

**Comment by cjolif** [comment]
I think this was "fixed" by a2cf44ed37f2472791255426f1f2ff43e0182470 that introduced transition property?
