### ISSUE TITLE
build errors II (small typo)

### ISSUE THREAD

**Issue by jankel** [dmachi/dojox_application#156]
Looks like a typo in master ./build/discoverAppConfig.js line 84 & 86 since push returns the number of array-elements. 

Wrong: 

``` javascript
mids = mids.push(config.transit);
//[...]
mids = mids.push("dojox/css3/transit");
```

Right:

``` javascript
mids.push(config.transit);
//[...]
mids.push("dojox/css3/transit");
```

Thx for the great project! :-)
Jan

**Comment by cjolif** [comment]
oups, thanks I will fix that one. Sorry.

**Comment by jankel** [comment]
Wow - already fixed - my appreciation!!
