### ISSUE TITLE
Transition.js is harcoding "center" as the constraint for some calls

### ISSUE THREAD

**Issue by cjolif** [dmachi/dojox_application#159]
This must be investigated why. If that is expected we must document in the code why and if not that must be changed.

Once done this will allow to understand what to pass as nextView parameter to the decativate calls just next to it.

**Comment by edchat** [comment]
I have started on code to remove the check for center which will call deactivate on all selectedChildren. I will clean it up and merge it soon.

**Comment by edchat** [comment]
This is fixed.
