### ISSUE TITLE
borderLayoutApp test file name issue

### ISSUE THREAD

**Issue by fdlane** [dmachi/dojox_application#202]
may be related to https://github.com/dmachi/dojox_application/issues/197

Test does not display because the file name in the test borderLayoutApp has a filename error.

```
require(["./borderLayoutApp.js"], function(){
```

should be

```
require(["./borderlayoutApp.js"], function(){
```

**Comment by cjolif** [comment]
That's really strange. I wonder why the L was changed to upper-case as indeed the file name is lower-case. I guess we need @edchat to be back to better understand what's going on. My choice would be to capitalize the L in the file name not move the require call back to lower-case.

**Comment by dmachi** [comment]
This likely just got missed because the mac fs is not case sensitive by default.

**Comment by edchat** [comment]
Sorry about this, I think I did the rename in my repo, but missed it when I pushed it to github somehow.
