### ISSUE TITLE
Changing the orientation on iphone breaks the display

### ISSUE THREAD

**Issue by cjolif** [dmachi/dojox_application#52]
This can be reproduced on the todoApp. This apparently comes from the Layout controller that only listens to onresize not onorientation change.

See more details in cjolif/dojo-todo-app#86

**Comment by edchat** [comment]
Change was to bind to browsers orientationchange event for ios otherwise bind to browsers resize event.  
This can be closed when the pull request is merged.

**Comment by cjolif** [comment]
I'm closing this following Ed's commit. That said there might still be improvements to be done to the Layout controller. At least on todoApp when rotating the device (iOS) the background is partially black, partially grey. This does not look very good and could certainly be improved (don't know if that is a app or todoApp issue).
