### ISSUE TITLE
After switching views layout is messed up.

### ISSUE THREAD

**Issue by mortelee** [dmachi/dojox_application#62]
Hi

It was adviced to me I should submit issues here when I found problems related to dojox.app.

I'm facing some problems when switching views.
How to reproduce

1) Go from view 1 to view 2
2) Resize the browser window
3) Go from view 2 to view 1
-> Now (somettimes) the layout is messed up. After again resizing the browser window the layout is good.

See also http://dojo-toolkit.33424.n3.nabble.com/1-8beta-Sereral-re-size-issues-td3987241.html#a3987364  (issue 3)  for used code and screenshots

**Comment by cjolif** [comment]
well if I'm not mistaken you are doing the layout yourself instead of relying on the Layout controller. So maybe your code is doing something wrong?

**Comment by mortelee** [comment]
I use the dojox.mobile.FixedSplitter to layout the header, main content and footer. The only thing I do dynamically is setting the height of the scrollable views.
Maybe than the problem is in the splitters, but I don't do anything strange there...

**Comment by cjolif** [comment]
@mortelee to trigger the Layout controller you need to put region="center" on the FixedSplitter of view1. Have you tried that? Does it solve your issue? Also I'm pretty sure that once you have done that you can get rid of your own layout in view1.

**Comment by mortelee** [comment]
I've used the region property, but that didn't help. Also I don't do any layouting of myself on the views. I rely on the FixedSplitter to layout the header, main content and footer.

**Comment by cjolif** [comment]
@mortelee I have edited view1/view1.html in _your_ example taking my advice into account and everything works fine. I have changed:

``` html
  <div data-dojo-type="dojox.mobile.FixedSplitter" data-dojo-props='orientation:"V", variablePane:1'>
```

to 

``` html
  <div data-dojo-type="dojox.mobile.FixedSplitter" data-dojo-props='orientation:"V", variablePane:1' region="center">
```

Do you tell me that doing that _exact_ same change on your sample application and using latest dojox/app code you get a different behavior than I do? If yes we need to understand what's the different between your environment and mine... Which platform are you experiencing the issue with for example?

**Comment by mortelee** [comment]
You're code works. I placed the regfion prop on the spliiterpane, that didn't work.

But now the scrollable views only are correctly updated when switching from view 2 to view 1. When resizing the browser the height of the scrollable views is incorrect.

**Comment by mortelee** [comment]
Fixed height of scrollable viewissue. At the end it was a css problem.
Thanks for your help!
