### ISSUE TITLE
scrollable.js bad api doc

### ISSUE THREAD

**Issue by wkeese** [dmachi/dojox_application#71]
The non-function values aren't documented correctly, see http://bugs.dojotoolkit.org/ticket/15440 and http://bugs.dojotoolkit.org/ticket/15438.

**Comment by cjolif** [comment]
As of today this doc should not be public at all actually. The long term plan is to merge that with dojox/mobile version.

**Comment by edchat** [comment]
We are now using the dojox/mobile version of scrollable.js
