### ISSUE TITLE
Having main.js automatically load the Load, Transition and Layout controllers prevents applications from being able to override those controllers.

### ISSUE THREAD

**Issue by edchat** [dmachi/dojox_application#76]
I think the automatic loading of the controllers should be optional, (done by default) so that the application can replace one of those controllers if necessary.
The config section to prevent the automatic loading of the controllers would be as follows, and each of the 3 controllers would need to be specified if "noAutoLoadControllers" : is set to true.

``` javascript
    "noAutoLoadControllers" : true,

    "controllers": [
        "dojox/app/controllers/Load",
        "dojox/app/controllers/Transition",
        "dojox/app/controllers/Layout",
        "dojox/app/controllers/History"
    ],
```

**Comment by cjolif** [comment]
As far as I can see this is not documented? If that is the case I think documentation should be fixed (http://livedocs.dojotoolkit.org/dojox/app).
