### ISSUE TITLE
There are problems running the app tests on IE, even after removing the History controller which does not support IE.

### ISSUE THREAD

**Issue by edchat** [dmachi/dojox_application#78]

**Comment by edchat** [comment]
The Transition controller (app/controllers/Transition.js) is using "dojox/css3/transit" which does not work on IE.

**Comment by cjolif** [comment]
There are three subpoints:
a/ With IE10 coming we should make sure dojox/css3 is updated to work on IE10. 
b/ We need to make sure each controller is _really_ optional and thus Transition.js can be removed if you don't want transitions and/or your platform don't support them
c/ We need to make sure that even when Transition is included (for it to work on Webkit / FF browsers), it does not break the behavior on IE9- (i.e. call dojox/css3 inside a has() that excludes IE9-).

c/ is probably a bug fix, other ones are more type of enhancements.

**Comment by cjolif** [comment]
See #81 & #82 for dojo18 & master pull requests
