### ISSUE TITLE
Update the View object for better support of desktop apps

### ISSUE THREAD

**Issue by itamarro** [dmachi/dojox_application#96]
I'm working on a desktop application using the dojox.app framework. I realize it is not suitable for this job just yet, so I'm trying to raise some points here that I think are relevant in the ongoing work to make it applicable to desktop applications. I must apologize in advance if I got something wrong at an understanding level, most of this is pretty bleeding edge and not very deeply documented so I could definitely be wrong here.

In this issue, I'd like to focus on the View class, specifically the _startup() method:
1. For child views, the region is basically always set to center. I think that in order to enable the kind of composite views a desktop app requires, more flexibility is required - e.g. perhaps giving the parent the ability to specify "openings" or regions where children views would be put. Not sure how this could/should be done currently.
2. The inline setting of the style to "width:100%; height:100%" - for me it has caused issues since it overrides my own style declarations (e.g. a page that would otherwise be properly laid out, got out of hand because this overriden my CSS defs. I'd suggest giving this reasonable default behavior, but allowing people to avoid having these style settings applied, so they can match their specific needs - and documenting how all of that should be done.
3. Additionally, I don't think the overriding of the IDs of the view elements is a good practice. I can imagine why it's needed, so if it is really a must, let me humbly suggested that it be better documented. I'd suggest adding to the relevant document (http://dojotoolkit.org/reference-guide/1.8/dojox/app/view.html): "Note that View will override the created view HTML element with an ID determined by the view hierarchy as specified in the app's configuration. This means you should not set an ID for your views in your templates or rely on your own ID in your CSS or code."

**Comment by edchat** [comment]
Thanks for the feedback.  I will add item 1 and 2 to the plan document "Dojo App Dev. 1.9 and/or 2.0 plans".
https://docs.google.com/document/d/1fe2qm1x_AHidYd2wNkG77tZgFIrvlt-ctGT0rpb-5F0/edit

For item 3, currently the ID is being used by the Load controller to determine if the view has already been created (with the same set of parents) and the view is reused instead of being created.  So for now we need to set the ID for the view.  So I will add the Note to the documentation.

**Comment by itamarro** [comment]
Great! Thank you very much.

**Comment by edchat** [comment]
I believe all of these issues have been covered in 1.9.
