### ISSUE TITLE
Transitions: Support transitionOptions for desktop apps as well

### ISSUE THREAD

**Issue by itamarro** [dmachi/dojox_application#97]
( Note: My disclaimer from the previous issue applies here as well. I'm doing my best to point out the relevant stuff, but could certainly be missing the mark in one way or another. )

Right now, trasitionOptions can only be used can be on dojox/mobile widgets which inherit from dojox/mobile/_ItemBase. There needs to be a way for this to work well in desktop apps as well.

Support for composite views (where i.e. a view can have two children, and each child initiates a transition to another view within the space of that child) would be very nice as well.

**Comment by cjolif** [comment]
I don't think we want to go in the business of modifying dijit widget set to directly support transition options in dojox/App itself. That said you can certainly code your desktop application to leverage them.
For example something like the following:

``` html
<script>
function onClick(){
  on.emit(this, 'startTransition', { bubbles: true, cancelable: true, detail: { target : 'otherview' } });
}
</script>
<button data-dojo-type="dijit/form/Button" data-dojo-props="onClick: onClick()"></button>
```

Having subclasses of Dijit that would do that for you would be a separate project I would say. Probably an interesting one but a different one.

Composite views are supported I think at least in master.

**Comment by itamarro** [comment]
To be honest, it's been a few months since I created this issue and since then I changed infrastructure in my project, so the exact need I had in mind is probably not 100% crystal to me as of this writing :)

That said, IIRC the idea was to have something more integrated, as part of the application definition JSON. I do understand the design constraints you mention, of course, but that was the original idea in this issue.

**Comment by cjolif** [comment]
Ok. In case you interested in pursuing this as I understand you moved to something else, does it mean that in addition to what we have today the ability to define the transition type in the config ("slide" ...) you'd like to be able to define there the other transition options as well? Like direction...?  Or that would like to define in the JSON itself the entire transition process like click on this button leads to that view etc... thanks for your feedback.

**Comment by itamarro** [comment]
More of the latter. The idea was to have the transitions as an inherent part of the app definition in the JSON itself, as was possible for mobile, for desktop apps. So it's a form of wiring the app (and its routing). The type of transition (slide etc.) would just be an aspect of that definition, as a nice-to-have.

**Comment by dmachi** [comment]
@itamarro I think you have the general idea of what I'd like to see accomplished.  All that said, when this was first begun I expected (and still expect) that future dijit's or revisions of dijit will use native event bubbling for many of its interactions.  When this is the case, it should be easier to be more consistent between platforms.  Currently, I think a dev would either have to create a new desktop widget (say a tab container) that works with event bubbling and transitions like the mobile side or alternatively extend an existing dijit to understand the json config and use the information therein to set itself up.  Of course this latter option would not mean that css3 transitions would be used, but it would allow the configuration of relationships between the components dynamically.

Anyway, I think you have the idea correct, there just aren't many existing dijits that behave this way.  I didn't really expect any of that part to be on par with the mobile definitions until Dijit for dojo 2.x is more defined.  I have made a case in the past for increasing use of event bubbling for interactions between dijits and their containers.

**Comment by itamarro** [comment]
@dmachi Got it. Makes sense - thank you for the detailed explanation. I guess it's one of those things to look forward to, then :)

**Comment by itamarro** [comment]
So, close the issue? Or leave it till it is indeed resolved sometime in the future?

**Comment by dmachi** [comment]
I'll close it for now since this is our general intent, but may be sometime before we get all the way there.
